---

name: Build documents
'on':
  push:
    branches:
      - main
      - composite-action # TODO Delete

jobs:
  build:
    runs-on: ubuntu-latest
    container: bergentroll/pali-english-recitations-builder:latest
    steps:
      - uses: bergentroll/sasanarakkha-build-ebooks-action@v1
        with: {}
